"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv  import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=BASE_DIR / ".env")

AUTH_USER_MODEL = "api.CustomUser"  # ✅ Tell Django to use CustomUser model

# SECRET_KEY = ""
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"


DEBUG = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # or DEBUG if you want everything
    },
    "loggers": {
        "bulk_email": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}



ALLOWED_HOSTS = ['churn.prowesstics.space','churn.ai.prowesstics.co.in','churn.ai.prowesstics.co.in/flask','churn.prowesstics.space/flask', "localhost",
    "127.0.0.1", "localhost:5173/"]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",  # ✅ Allow all users to register
    ],
    "DEFAULT_RENDERER_CLASSES": (  # ✅ Enable Browsable API
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer" if DEBUG else "rest_framework.renderers.JSONRenderer",
    ),
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes = 5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "TOKEN_USER_CLASS": "api.CustomUser",
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",  # ✅ Enables JWT Blacklist
    "corsheaders",
    "api",
    "bulk_email",
    "analytics",
    "configurations",
    "health_monitor",
    'celery',
    'dataconnectors',
    ]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "analytics.middleware.RequestMetricsAndDownloadMiddleware",
    
]

ROOT_URLCONF = 'myproject.urls'

CSRF_TRUSTED_ORIGINS = [
    "https://churn.prowesstics.space",
    "https://churn.ai.prowesstics.co.in",
    "http://localhost:5173",
]


# Celery Configuration
CORS_ALLOWED_ORIGINS = [
    "https://churn.prowesstics.space",
    "https://churn.ai.prowesstics.co.in",
    "http://localhost:5173",
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default backend
    'api.backends.RoleAuthenticationBackend',     # ✅ Your custom backend path
]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ENCRYPTION_KEY = b'oL4n0PkeSLwj3xHzgbTN_6WbWHteDL7gMzF4tQ2uUpM='


WSGI_APPLICATION = 'myproject.wsgi.application'

CELERY_BROKER_URL = 'sqla+sqlite:///celerydb.sqlite'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("AUTH_DB_NAME", "postgres"),
        'USER': os.getenv("AUTH_DB_USER", "appadmin"),
        'PASSWORD': os.getenv("AUTH_DB_PASSWORD", "prowesstics"),
        'HOST': os.getenv("AUTH_DB_HOST", "20.244.31.74"),
        'PORT': os.getenv("AUTH_DB_PORT", "5432"),
        'CONN_MAX_AGE': 60,
        'OPTIONS': {
            'options': '-c search_path=user_credentials'
        }
    }}

EXTERNAL_DATABASES = {

'DB_SSBI_Excel' : {
    "dbname":'SSBI',
    "user": "appadmin",
    "password": "prowesstics",
    "host": "20.244.31.74",
    "port": "5432",
},

'DB_SSBI' : {
    "dbname":"Automation",
    "user": "appadmin",
    "password": "prowesstics",
    "host": "20.244.31.74",
    "port": "5432",
},

'DB_Auto' : {
    "dbname": "Automation",
    "user":"appadmin",
    "password": "prowesstics",
    "host": "20.244.31.74",
    "port": "5432",
},

'DB_CLV_SRC' : {
    'host': "20.244.31.74",
    'database': "postgres",
    'user': "appadmin",
    'password': "prowesstics",
    'port': "5432",
},

'DB_CLV_TGT' :{
    'host': "20.244.31.74",
    'database': "Automation",
    'user': "appadmin",
    'password': "prowesstics",
    'port': "5432",
    'schema': "clv",
},

'DB_CLV_PRED': {
    'host': "20.244.31.74",
    'database': "Automation",
    'user': "appadmin",
    'password':"prowesstics",
    'port': "5432"
},

'DB_PRED_SRC' : {
    'host': "20.244.31.74",
    'database':"postgres",
    'user': "appadmin",
    'password': "prowesstics",
    'port': "5432"
},

'DB_PRED_TGT' : {
    'host': "20.244.31.74",
    'database': "Automation",
    'user': "appadmin",
    'password': "prowesstics",
    'port': "5432"
},

'DB_REASON_DB': {
    'host':"20.244.31.74",
    'port':"5432",
    'user': "appadmin",
    'password': "prowesstics",
    'database': "Automation",
    'schema': "prediction",
    'table': "rancat_prediction_jfmamuj"
},

'DB_REASON_BUCKET_DB' : {
    "host": "20.244.31.74",
    "port": "5432",
    "database": "Automation",
    "user": "appadmin",
    "password": "prowesstics"
},

'DB_SEGMENT_DB' : {
    'host': "20.244.31.74",
    'database': "Automation",
    'user': "appadmin",
    'password': "prowesstics",
    'port': "5432"
},

'DB_PAST' :{

    'host': "20.244.31.74",
    'dbname': "Automation",
    'user': "appadmin",
    'password': "prowesstics",
    'port': "5432"

},

'DB_New_Pred' :{

    'host': "20.244.31.74",
    'dbname': "updated_ui_db",
    'user': "appadmin",
    'password': "prowesstics",
    'port': "5432"

},

'DB_New_Past' :{

    'host': "20.244.31.74",
    'dbname': "updated_ui_db",
    'user': "appadmin",
    'password': "prowesstics",
    'port': "5432"

},
'DB_Conv_AI' :{

    'host': "20.244.31.74",
    'dbname': "liberty_updated",
    'user': "appadmin",
    'password': "prowesstics",
    'port': "5432"

},

'DB_Azure_Airflow' :{

    'host': "98.70.38.133",
    'dbname': "liberty_updated",
    'user': "appadmin",
    'password': "prowesstics",
    'port': "5432"

},

'DB_Azure_Prochurn_Airflow' :{

    'host': "135.235.139.203",
    'dbname': "prochurn",
    'user': "appadmin",
    'password': "prowesstics",
    'port': "5432"

},



}

# DATABASE_ROUTERS = ['api.database_router.MultiDBRouter']
 
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024 * 1024  # 10GB (adjust as needed)

# ✅ Enable streaming uploads
FILE_UPLOAD_HANDLERS = ["django.core.files.uploadhandler.TemporaryFileUploadHandler"]

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True 
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT"
]
