# Generated by Django 5.1.6 on 2025-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_processeddata_uploadedfile_alter_process_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processeddata',
            options={},
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterModelTable(
            name='processeddata',
            table=None,
        ),
    ]
