# Generated by Django 5.1.6 on 2025-07-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_processeddata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnedPolicy',
            fields=[
                ('policy_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('biz_type', models.CharField(max_length=50)),
                ('vehicle_age', models.IntegerField()),
                ('rto_location', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('vehicle_reg_no', models.CharField(max_length=20)),
                ('total_premium_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('corrected_name', models.CharField(max_length=150)),
                ('policy_tenure', models.IntegerField()),
                ('policy_end_date', models.DateField()),
                ('main_reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'churned_policies',
                'ordering': ['policy_end_date'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
