# Generated by Django 5.1.6 on 2025-07-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_churnedpolicy_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChurnedPolicy',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='ProcessedData',
        ),
    ]
