# Generated by Django 5.1.6 on 2025-07-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_churnedpolicy_delete_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='temp_field',
            field=models.BooleanField(default=False),
        ),
    ]
