# Generated by Django 5.1.6 on 2025-07-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='temp_field',
        ),
    ]
