# Generated by Django 5.1.6 on 2025-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_date_of_birth_customuser_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='path',
            field=models.CharField(default='Default User', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
