# Generated by Django 5.1.6 on 2025-07-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_page_path_alter_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
