# Generated by Django 5.1.6 on 2025-07-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_page_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='designation',
        ),
    ]
