# Generated by Django 5.1.6 on 2025-07-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_customuser_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sector',
        ),
    ]
