# Generated by Django 5.1.6 on 2026-01-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_segmentationconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentationconfig',
            name='user',
        ),
    ]
