# Generated by Django 5.1.6 on 2026-01-22 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_segmentmetricconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='base_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='fetched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
