# Generated by Django 5.1.6 on 2026-01-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_alter_currencyrate_base_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('from_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GmailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(max_length=254)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_cred', to='configurations.emailconfig')),
            ],
        ),
        migrations.CreateModel(
            name='GmailOAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(default='desktop', max_length=32)),
                ('client_id', models.CharField(max_length=512)),
                ('client_secret', models.CharField(max_length=512)),
                ('redirect_uris', models.JSONField(blank=True, default=list)),
                ('raw_json', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_client', to='configurations.emailconfig')),
            ],
        ),
    ]
