# Generated by Django 5.1.6 on 2025-11-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts_ms', models.BigIntegerField(db_index=True)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('user_email', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('user_name', models.CharField(blank=True, max_length=256, null=True)),
                ('route', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'ts_ms'], name='analytics_a_type_024b4e_idx'), models.Index(fields=['session_id', 'ts_ms'], name='analytics_a_session_eac8a3_idx'), models.Index(fields=['user_email', 'ts_ms'], name='analytics_a_user_em_5004dd_idx')],
            },
        ),
    ]
