# Generated by Django 5.1.6 on 2025-12-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('route', models.CharField(db_index=True, max_length=256)),
                ('method', models.CharField(max_length=8)),
                ('status_code', models.SmallIntegerField()),
                ('duration_ms', models.FloatField()),
                ('is_error', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['ts'], name='analytics_r_ts_9af727_idx'), models.Index(fields=['route', 'ts'], name='analytics_r_route_d6cb91_idx'), models.Index(fields=['status_code', 'ts'], name='analytics_r_status__62010b_idx')],
            },
        ),
    ]
